### ISSUE TITLE
[FTU] -  Make code more readable

### ISSUE THREAD

**Issue by rutvikpadhiyar000** [OfficialAsherPlayz/python-math-calculator#6]
**Is your feature request related to a problem? Please describe.**

While code is currently small it is still little difficult to understand.

**What is the feature request?**

make code more readable.

**Describe the solution you'd like**

Add better comments, more descriptive variable names and make code simpler.

**Describe alternatives you've considered**

**Additional context**

**Comment by rutvikpadhiyar000** [comment]
i would like to sanitize code.

**Comment by CodeAsherPlayz** [comment]
Sure, you can open a pull request and link it to this issue. :D Thanks for dropping by!
